print("\n===Switch===")
mes = int(input("Digite um número de 1 a 12: "))
match mes:
    case 1: print("Janeiro\n")
    case 2: print("Fevereiro\n")
    case 3: print("Março\n")
    case 4: print("Abril\n")
    case 5: print("Maio\n")
    case 6: print("Junho\n")
    case 7: print("Julho\n")
    case 8: print("Agosto\n")
    case 9: print("Setembro\n")
    case 10: print("Outubro\n")
    case 11: print("Novembro\n")
    case 12: print("Dezembro\n")
    case _: 
        print("Erro: Número inválido! Digite um valor entre 1 e 12.\n")
